version: "3.6"

services:
  server:
    build: .
    container_name: server_auth_app
    command: sh -c './wait-for postgresql-local:5432 -t 55 -- npm start'
    ports:
      - ${PORT}:8080
    depends_on:
      - postgresql-local
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  postgresql-local:
    image: postgres:14.1-alpine
    container_name: postgresql-local
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB=authentication_app
    volumes:
      - /tmp/postgresql_data/:/var/lib/postgresql/data
