version: "3.6"

services:
  server:
    build: .
    command: sh -c './wait-for postgres-test:5432 -t 55 -- npm run dev'
    ports:
      - 8080:8080
    depends_on:
      - postgres-test

  postgres-test:
    image: postgres:14.1-alpine
    container_name: postgres-test
    environment:
      - POSTGRES_USER=alexandraclaudiabrad
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - /tmp/postgresql_data/:/var/lib/postgresql/data
