version: "3.6"

services:
  server-test:
    build: .
    env_file: .env
    container_name: server_auth_app_test
    command: sh -c './wait-for postgresql-test:5432 -t 55 -- npm run test:compose'
    ports:
      - ${PORT}:8080
    depends_on:
      - postgresql-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgresql-test:
    image: postgres:14.1-alpine
    container_name: postgresql-test
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-test:/var/lib/postgresql/data

volumes:
  postgresql-test:
    driver: local
