version: "3.6"

services:
  server:
    build: .
    env_file: .env
    container_name: server_auth_app
    command: sh -c './wait-for postgresql-local:5432 -t 55 -- npm start'
    ports:
      - ${PORT}:8080
    depends_on:
      - postgresql-local
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgresql-local:
    image: postgres:14.1-alpine
    container_name: postgresql-local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql-local:/var/lib/postgresql/data

volumes:
  postgresql-local:
    driver: local
