version: "3.6"

services:
  server-test:
    build: .
    container_name: server_auth_app_test
    command: sh -c './wait-for postgresql-test:5432 -t 55 -- npm run dev'
    ports:
      - 8080:8080
    depends_on:
      - postgresql-test

  postgresql-test:
    image: postgres:14.1-alpine
    container_name: postgresql-test
    restart: always
    environment:
      - POSTGRES_USER=alexandraclaudiabrad
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=authentication_app_test
    volumes:
      - /tmp/postgresql_data/:/var/lib/postgresql/data
